services:
  - type: web
    name: frescoenvivo
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start -- -H 0.0.0.0 -p $PORT
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM_NAME
        sync: false
      - key: CUSTOM_DOMAIN_TARGET
        sync: false
      - key: BRAND_LOGO_URL
        sync: false
      - key: BRAND_SUPPORT_URL
        sync: false
      - key: BRAND_INSTAGRAM_URL
        sync: false
